name: 'Auto Assignment'
description: 'Automatically assigns when a pull request is opened.'
author: 'kyoya0819'

inputs:
    token:
        description: 'GitHub token'
        required: true
    users:
        description: 'Users name of the person to be assigned. (JSON format)'
        required: true
    count:
        description: 'Number of Users to be assigned. If not entered, everyone will be assigned.'
        required: false

runs:
    using: 'node12'
    main: 'dist/index.js'