name: Eslint

on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]

    workflow_dispatch:

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                node-version: "15"
                cache: yarn

            - name: Install
              run: yarn install

            - name: Eslint
              run: yarn lint